# Use Dockerized infrastructure
sudo: false

branches:
  only:
  - master

language: node_js
node_js:
  - "6"

services:
  - docker

cache:
  directories:
    - "$HOME/google-cloud-sdk/"

env:
  global:
    - GOOGLE_APPLICATION_CREDENTIALS=~/gcloud-service-key.json
    - PROJECT_NAME_STG=bloo-cloud
    - CLUSTER_NAME_STG=bloo-cluster
    - PROJECT_NAME_PRD=bloo-cloud
    - CLUSTER_NAME_PRD=bloo-cluster
    - CLOUDSDK_COMPUTE_ZONE=europe-west3-a
    - DOCKER_IMAGE_NAME=bloo-graph
    - KUBE_DEPLOYMENT_NAME=bloo-graph
    - KUBE_DEPLOYMENT_CONTAINER_NAME=bloo-graph

before_deploy:
  - if [ ! -d "$HOME/google-cloud-sdk/bin" ]; then rm -rf $HOME/google-cloud-sdk; export CLOUDSDK_CORE_DISABLE_PROMPTS=1; curl https://sdk.cloud.google.com | bash; fi
  - source /home/travis/google-cloud-sdk/path.bash.inc
  - gcloud --quiet version
  - gcloud --quiet components update
  - gcloud --quiet components install beta
  - gcloud --quiet components update kubectl

deploy:
  - provider: script
    script: ./scripts/deploy.sh
    skip_cleanup: true
    on:
      branch: master
